### PR TITLE
add TwoSum.py

### PR DESCRIPTION
**Pull request by gympohnpimol**
Created TwoSum.py ☺️
This is the most popular among code interview

### CODE REVIEW

**Review by Aman22sharma — CHANGES_REQUESTED** [review]
Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure.

**Comment by gympohnpimol** [comment]
> Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure.

Thank you for your information. I have already correct the file structure.

**Review by Aman22sharma — APPROVED** [review]

**Comment by Aman22sharma** [comment]
Thank you for your contribution

**Comment by gympohnpimol** [comment]
> Thank you for your contribution

Does the project seem to exclude?

**Pull request merged**
