### PR TITLE
Create concept-Datatypes_PP6975H

### PR DESCRIPTION
**Pull request by devnarayanp02**

### CODE REVIEW

**Review by Aman22sharma — CHANGES_REQUESTED** [review]
Still you have done some mistake read the readme.md carefully and follow the steps. you missed the file name extension that is .py and you have to add these inside you the top of you file make these changes
// AUTHOR: Your Name
// Python3 Concept: your python3 concept that you want to add (ex: variable,datatypes etc)
// GITHUB: your github profile link

//Add your python3 concept below

**Comment by Aman22sharma** [comment]
after making changes you can create a pull request in this same branch ok no need to create another branch

**Comment by devnarayanp02** [comment]
Sorry, i will try again.

**Review by Aman22sharma — APPROVED** [review]

**Comment by devnarayanp02** [comment]
Thankyou

**Comment by Aman22sharma** [comment]
Hacktoberfest-accepted

**Comment by devnarayanp02** [comment]
thankyou

**Pull request merged**
