### PR TITLE
Provide an example package and module for others who may want to lear…

### PR DESCRIPTION
**Pull request by SoWrongImRight**
…n to provide their code for use

### CODE REVIEW

**Review by Aman22sharma — APPROVED** [review]
Thank you for your valuable contributions. moving forward for more such kind of contribution from your side

**Comment by SoWrongImRight** [comment]
I added in a dice rolling program, as well.  I don't know if I need a separate pull request for that.  Sorry, I'm new to the collaboration side of Github.

**Comment by SoWrongImRight** [comment]
Am I supposed to do something more?

**Review by Aman22sharma — CHANGES_REQUESTED** [review]
You have to follow the readme.MD carefully. you didn't add your details in dicreroll.py and also you have changed your file name diceroll_SoWrongImRight.py. make these changes

**Comment by SoWrongImRight** [comment]
Corrected the files to follow the README.md specifications.

**Review by Aman22sharma — APPROVED** [review]

**Pull request merged**
